/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.reserva.Item;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import View.CadastroPessoa;
import View.Reserva;

public class CadastroItem extends javax.swing.JFrame {

    public CadastroItem() {
        initComponents();
    }
    public static ArrayList<Item> itens = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeItem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numSerie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItem = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cadPessoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do item");

        btnAdicionar.setText("adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca");

        jLabel3.setText("Descricao");

        jLabel4.setText("numero de serie");

        tabelaItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "marca", "descricao", "numSerie"
            }
        ));
        tabelaItem.setUpdateSelectionOnSort(false);
        tabelaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaItemMouseClicked(evt);
            }
        });
        tabelaItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaItemKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaItem);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDelete.setText("Deletar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cadPessoa.setText("Cadastrar Pessoa");
        cadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPessoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cadastrar Item");

        btna.setText("jButton1");
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(descricao)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnAtualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnDelete)
                        .addGap(58, 58, 58)
                        .addComponent(btna))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(marca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(cadPessoa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadPessoa)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnDelete)
                    .addComponent(btna))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        if (!testaCampos()) {
            DefaultTableModel dtmAdd = (DefaultTableModel) tabelaItem.getModel();

            itens.add(new Item(nomeItem.getText(), marca.getText(), descricao.getText(), Integer.parseInt(numSerie.getText())));

            Object[] tabela = {nomeItem.getText(), marca.getText(), descricao.getText(), numSerie.getText()};
            dtmAdd.addRow(tabela);

            JOptionPane.showMessageDialog(null, "Adicionado com sucesso");
            limpaCampos();

        } else {
            JOptionPane.showMessageDialog(null, "precisa preencher todos os campos");
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tabelaItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaItemKeyReleased

    }//GEN-LAST:event_tabelaItemKeyReleased

    private void tabelaItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaItemMouseClicked

        if (tabelaItem.getSelectedRow() != -1) {
            nomeItem.setText(tabelaItem.getValueAt(tabelaItem.getSelectedRow(), 0).toString());
            marca.setText(tabelaItem.getValueAt(tabelaItem.getSelectedRow(), 1).toString());
            descricao.setText(tabelaItem.getValueAt(tabelaItem.getSelectedRow(), 2).toString());
            numSerie.setText(tabelaItem.getValueAt(tabelaItem.getSelectedRow(), 3).toString());
        }

    }//GEN-LAST:event_tabelaItemMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (tabelaItem.getSelectedRow() != -1) {

            Object[] opcoes = {"Confirmar", "Cancelar"};
            if (JOptionPane.showOptionDialog(null, "Deleja alterar este registro?", "Alterar Registro", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]) == 0) {

                DefaultTableModel dtmAlt = (DefaultTableModel) tabelaItem.getModel();

                Object[] row = {nomeItem.getText(), marca.getText(), descricao.getText(), numSerie.getText()};

                itens.set(tabelaItem.getSelectedRow(), new Item(nomeItem.getText(), marca.getText(), descricao.getText(), Integer.parseInt(numSerie.getText())));

                for (int i = 0; i < dtmAlt.getColumnCount(); i++) {

                    dtmAlt.setValueAt(row[i], tabelaItem.getSelectedRow(), i);
                }
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso");

                limpaCampos();
            } else {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione Linha para alterar");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (tabelaItem.getSelectedRow() != -1) {

            Object[] opcoes = {"Confirmar", "Cancelar"};

            if (JOptionPane.showOptionDialog(null, "Deleja deletar este registro?", "Deletar Registro", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]) == 0) {

                DefaultTableModel dtmDel = (DefaultTableModel) tabelaItem.getModel();

                itens.remove(tabelaItem.getSelectedRow());

                dtmDel.removeRow(tabelaItem.getSelectedRow());

                limpaCampos();
            } else {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione Linha para deletar");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPessoaActionPerformed

        CadastroPessoa cadastroPessoa = new CadastroPessoa();
        cadastroPessoa.setVisible(true);
        dispose();

    }//GEN-LAST:event_cadPessoaActionPerformed

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed
        Reserva res = new Reserva();
        res.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CadastroItem cadastroItem = new CadastroItem();
                cadastroItem.setVisible(true);
            }
        });
    }

    public void limpaCampos() {
        nomeItem.setText("");
        marca.setText("");
        descricao.setText("");
        numSerie.setText("");
    }

    public boolean testaCampos() {

        boolean cNome = nomeItem.getText().equals("") || nomeItem.getText() == null;
        boolean cMarca = marca.getText().equals("") || marca.getText() == null;
        boolean cDescricao = descricao.getText().equals("") || descricao.getText() == null;
        boolean cNumSerie = numSerie.getText().equals("") || numSerie.getText() == null;

        return (cNome || cMarca || cDescricao || cNumSerie);
    }

    public void addTab() {

        if (!itens.isEmpty()) {
            
            DefaultTableModel dtm = (DefaultTableModel) tabelaItem.getModel();
            
            for (int j = 0; j < itens.size(); j++) {
                
                Object[] rw = {itens.get(j).getNome(), itens.get(j).getMarca(), itens.get(j).getDescricao(), itens.get(j).getNumSerie()};
                dtm.addRow(rw);
                
            }
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btna;
    private javax.swing.JButton cadPessoa;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nomeItem;
    private javax.swing.JTextField numSerie;
    private javax.swing.JTable tabelaItem;
    // End of variables declaration//GEN-END:variables
}
